name: Visual Algorithm by Prabhat
on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker image
      run: |
        docker build -t my-visual-algorithm-app .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image
      run: |
        docker tag my-visual-algorithm-app ${{ secrets.DOCKER_USERNAME }}/my-visual-algorithm-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-visual-algorithm-app:latest
